package enums;

/**
 * @author Hans Schollaardt
 *
 */
public enum MessageType {
	HAVE_WORKMEETING, HAVE_GATHERMEETING, WORK, NOTIFY_JOINED_MEETING, NOTIFY_MEETING_ENDED, NOTIFY_AVAILABLE_GATHER, NOTIFY_AVAILABLE_WORK, NOTIFY_AVAILABLE_BLACK, NOTIFY_MEETING_STARTED, JOIN_MEETING, MEET_SAINT, MEETING_IN_PROGRESS
}
